<script type="text/javascript">
    function qq(value,name){
        alert(value+":"+name)
    }
</script>
<input id="ss" class="easyui-searchbox"
        searcher="qq"
        prompt="Please Input Value" menu="#mm" style="width:350px"></input>

<div id="mm" style="width:120px">
    <div name="all" iconCls="icon-ok">All News</div>
    <div name="sports">Sports News</div>
</div>
<!--<a href="#" onClick ="$('#tree-items').datagrid('reload');">click</a>-->