<script type="text/javascript">
    function qq(value,name){
        alert(value+":"+name)
    }
</script>
<input id="ss" class="easyui-searchbox"
        searcher="qq"
        prompt="Wyszukiwany" menu="#mm" style="width:350px"></input>

<div id="mm" style="width:120px">
    <div name="all" >Wszędzie</div>
    <div name="name">Nazwa</div>
    <div name="short_desc">Krótki opis</div>
    <div name="desc">Opis</div>
</div>
<!--<a href="#" onClick ="$('#tree-items').datagrid('reload');">click</a>-->