<?php
/**
 * Wyswietlanie ładnie wygenerowanej daty
 */
$row = $this->row;
?>
<?php if ($row['date_add']): ?>
    <span title="Od daty dodania mineło: <?= $this->TimePassed(strtotime($row['date_add'])); ?>, plik został dodany o godzinie: <?= date('h:m:s', strtotime($row['date_add'])); ?>">
    <?= date('d-m-Y', strtotime($row['date_add'])); ?>
    </span>
<?php else: ?>
        --
<?php endif; ?>
