<?php
/**
 * @author Arnold Sikorski
 *
 * Informacje do modułu zarzadzania stronami dynamicznymi
 */
?>
<script type="text/javascript">
    $(document).ready(function() {
        $('#contact-box-container').dialog({
            width:600,
            modal:false
        });
        /*textarea*/
        $('textarea#message-area').tinymce({
            // Location of TinyMCE script
            script_url : '/js/tiny_mce/tiny_mce.js',

            // General options
            theme : "advanced",
            plugins : "fullscreen",
            //styleselect,formatselect,fontselect,fontsizeselect
            //formatselect,fontselect,fontsizeselect
            // Theme options
            theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,|,fullscreen",
            theme_advanced_buttons2 : "",
            theme_advanced_buttons3:"",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_resizing : true,

            // Example content CSS (should be your site CSS)
            content_css : "css/content.css",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url : "lists/template_list.js",
            external_link_list_url : "lists/link_list.js",
            external_image_list_url : "lists/image_list.js",
            media_external_list_url : "lists/media_list.js",

            // Replace values for the template plugin
            template_replace_values : {
                username : "Some User",
                staffid : "991234"
            }
        });
    });
    function send(){
        $('#contact-form').form('submit',{
            onSubmit:function(){
                return $(this).form('validate');
            },
            success:function(data){
                $.messager.alert('Info', data, 'info');
                //alert(data);
            }
        });
    } 

</script>

<div id ="contact-box-container" buttons="#dlg-buttons-submit" title ="Kontakt z nami">
    <form id="contact-form" method="post">
        <table class="contact-table" style="width:100%;padding:5px;margin-top:5px;">
            <tbody><tr>
                    <td>Imię i Nazwisko:</td>
                    <td><input class="easyui-validatebox" type="text" name="name" required="true"></td>

                </tr>
                <tr>
                    <td>Adres Email:</td>
                    <td><input class="easyui-validatebox" type="text" name="email" required="true" validType="email"></input></td>
                </tr>
                <tr>
                    <td>Temat:</td>
                    <td><input class="easyui-validatebox" type="text" name="subject" required="true"></input></td>
                </tr>
                <tr>
                    <td>Wiadomość:</td>
                    <td><textarea id ="message-area" name="message" style="height:150px;width:450px"></textarea></td>
                </tr>
            </tbody>
        </table>

    </form>
    <div id="dlg-buttons-submit">
        <a href="<?php echo $this->options['contact']['www']; ?>" target ="_BLANK" class="easyui-linkbutton button-blue"  ><strong>Nasza strona www</strong></a>
        <a href="#" class="easyui-linkbutton button-blue"  onclick="send()"><strong>Wyślij</strong></a>
        <a href="#" style ="float:left;" class="easyui-linkbutton button-blue"  onclick="javascript:$('#contact-box-container').dialog('close')">Anuluj</a>
    </div>
</div>