
<div id ="preview-box-container"   
     shadow ="false" class="easyui-dialog"
     draggable ="true"
     resizable="true"
     closable ="false"

     title ="Podgląd strony"
     buttons="#dlg-buttons-action" >
    <iframe class ="iframe-no-border" style ="width:<?php echo $this->options['size']['width'];?>;height: <?php echo $this->options['size']['height'];?>;" src="<?php echo $this->options['http']['application'];?>">
Twoja przeglądarka nie obsługuje ramek pływających!
</iframe>
    <div id="dlg-buttons-action">
        <a href="#" class="easyui-linkbutton button-blue" title ="Zamknij"  ><strong>Zamknij okno</strong></a>
        <a target ="_BLANK" href="<?php echo $this->options['http']['application'];?>" class="easyui-linkbutton button-blue" title ="Zamknij"  >Powiększ</a>
    </div>
</div>