<div id="info">
    <ul>
        <li><a href="/">strona główna</a></li>
        <li><a href="/wylegarnia">wylęgarnia</a></li>
        <li><a href="#k">kontakt</a></li>
        <?php if(CMS_Users::checkStatus()!=CMS_Users::USER_ACTIVE):?>
        <li class="login"><a href="<?= $this->url(array(null),'userlogin')?>">logowanie</a></li>
        <?php else: ?>
        <li class="login"><a href="<?= $this->url(array(null),'usermyaccount')?>">moje konto</a></li>
        <?php endif; ?>
    </ul>
</div>
<div id="promo">
    <a href="/article">napisz i wygraj</a>
</div>
<?php
echo $this->layout()->menu->render();
?>
<div id="menusearch">
    <div class="search_input">
        <input class="input_search" value="szukaj na stronie..." type="text" />
        <input class="submit_search" type="submit" value=""/>
    </div>
    <div id="facebook">
        <a href="#facebook">find us on facebook</a>
    </div>
</div>