<div id="search-dialog-content" class="easyui-window"
     style="padding:5px;"
     title="Wyszukaj element"
     resizable ="false"
     minimizable="false"
     collapsible="false"
     maximizable="false"
     modal="true"
     closed="true">
    <div class ="inside-serach" style ="width:350px;"></div>
</div>
<!--Wyszukiwarka danych-->
<div id="tree-edit-dialog"
     class="easyui-dialog"
     closed="false"
     title ="Drzewo stron dynamicznych"
     maximizable ="true"
     style ="width:1100px;"
     resizable="false"
     buttons ="#dlg-buttons-tree-edit" >
    <div style ="float:left;width: 30%;">
        <div id="left-panel"
             class="easyui-panel"
             style="width:auto;height:auto;padding:10px;"
             closable="false"
             collapsible="false"
             minimizable="false"
             maximizable="false">
            <!--Drzewo kategorii-->
            <table id="tree-edit"
                   singleSelect="true" >
            </table>
            <!--/Drzewo kategorii-->
        </div>
    </div>
        <div id="right-panel"
             class="easyui-panel"
             style="width:auto;height:500px;padding:10px;float:right;"
             closable="false"
             collapsible="false"
             minimizable="false"
             maximizable="false">
            <!--Elementy kategorii-->

            <table id="tree-items" ></table>
            <!--/Elementy kategorii-->
        </div>

    </div>







    <div id="dlg-buttons-tree-edit">
        <a href="#" class="easyui-linkbutton button-blue" title ="Prześlij"  ><strong>Gotowe</strong></a>
        <a href="#" class="easyui-linkbutton button-blue" title ="Zamknij okno logowania" >Anuluj</a>
    </div>
</div>

<script type="text/javascript">



    $('#tree-edit').treegrid({
        rownumbers: false,
        title:'Foldery stron',
        animate:true,
        iconCls:'icon-save',
        collapsible:false,
        fitColumns:true,
        url:'/pl/sites/ajax/getsitestree',
        idField:'id',
        treeField:'name',
        showFooter:true,
        rowStyler:function(row){
            if (row.persons > 1){
                return 'background:#AAD684;color:#fff';
            }
        },
        columns:[[
                {title:'...',field:'active',width:20,align:'center'},
                {title:'Katalogi',field:'name',width:140},
                {title:'Akcja',field:'action',width:50,align:'center'}

            ]],
        onClickRow: function(row){
            //alert('test');

            if(row.id==1){
                $.messager.alert('Uwaga','Kategoria nadrzędna nie moze zawierać elementów');
            }else{
                load();
            }

        },
        onLoadSuccess: function(data){
<?php if ($this->row): ?>
                //Mam dane do expandu

                $('#tree-edit').treegrid('select',<?php echo (int) $this->row['category_id']; ?>);
                load();
                //selectRecord
                //alert('mam');

<?php endif; ?>
        }

    });
    /*usuwa korzeń*/
        function removeNode(rootId){


            $.messager.confirm('Uwaga!','Czy napewno chcesz usunąć ?',function(r){
                if (r){
                    $.ajax({
                        url: '/pl/sites/ajax/removeroot',
                        type: 'post',
                        dataType: 'json',
                        data: {
                            roots: rootId
                        },
                        success: function(data){
                            if(data.success){
                                $('#tree-edit').treegrid('reload', 0);
                                $.messager.alert('Uwaga','Element został usunięty');
                            }else{
                                $.messager.alert('Uwaga','Problem podczas dodawania elementu');
                            }
                        }
                    });
                }
            });


    }
    /*dodaje*/
        function addNewNode(selectedId){



                $.messager.confirm('Uwaga!','Czy napewno chcesz dodać nowy element',function(r){
                    if (r){
                        /**
                         * Dodawanie nowege korzenia
                         */
                        $.messager.prompt('Nazwa elementu', 'Podaj nazwe dodawanego elementu', function(r){
                            if (r){

                                var itemName = r;
                            }else{
                                var itemName = 'Nowy element';
                            }
                            $.ajax({
                                url: '/pl/sites/ajax/addnewnodetoroot',
                                type: 'post',
                                dataType: 'json',
                                data: {
                                    root: selectedId,
                                    name: itemName

                                },
                                success: function(data){
                                    if(data.success){
                                        //$('#tree-edit').tree('reload', 0);
                                        $('#tree-edit').treegrid('reload', 0);
                                        $.messager.alert('Uwaga','Element został dodany');

                                    }else{
                                        $.messager.alert('Uwaga','Problem podczas dodawania elementu');
                                    }
                                }
                            });
                        });

                    }else{
                        $.messager.alert('Uwaga','Anulowano dodawanie nowego elementu');
                    }
                });


    }
    /*usuwanie elementu*/
    function deteteItem(elementid){
            $.messager.confirm('Uwaga!','Czy napewno chcesz usunąć element?',function(r){
                if (r){

                    $.ajax({
                        url: '/pl/sites/ajax/removeitem',
                        global: false,
                        type: "POST",
                        data: {id : elementid},
                        dataType: "json",
                        async:false,
                        success: function(msg){
                            if(msg.success){
                                //$.messager.alert('Uwaga','Element został usuniety');
                                $('#tree-items').datagrid('reload');

                            }else{
                                $.messager.alert('Uwaga','Nie usunieto elementu');
                            }

                        }
                    });
                }

            });

        }
    /*usuwanie elementu*/
    function load(){

        var node = $('#tree-edit').treegrid('getSelected');
        if (node){
            $('#tree-items').datagrid({
                url:'/pl/sites/ajax/getelements?category_id='+node.id,
                view: detailview,
                loadMsg:'ładowanie danych , prosze czekać',
                rownumbers:true,
                nowrap: false,
                height:450,
                showFooter:true,
                pagination:true,
                singleSelect:true,
                onLoadSuccess:function(data){
                    /*poprawiam wyswietlanie*/
                    $('#tree-items').datagrid('fixDetailRowHeight',1);

                },
                detailFormatter:function(index,row){
                    return '<div class="ddv"></div>';
                },
                toolbar:[{
                        id:'btnadd',
                        text:'Dodaj',
                        handler:function(){
                            var node = $('#tree-edit').treegrid('getSelected');
                            if (node){
                                $.messager.confirm('Uwaga!','Czy napewno chcesz dodać nowy element?',function(r){
                                    if (r){
                                        $.ajax({
                                            url: '/pl/sites/ajax/additem',
                                            global: false,
                                            type: "POST",
                                            data: {category_id : node.id},
                                            dataType: "json",
                                            async:false,
                                            success: function(msg){

                                                if(msg.success){
                                                    $.messager.alert('Uwaga','Element został dodany');
                                                    $('#tree-items').datagrid('reload');

                                                }else{
                                                    $.messager.alert('Uwaga','nie dodano elementu');
                                                }
                                            }
                                        });
                                    }
                                });

                            }
                        }
                    },{
                        id:'btncut',
                        text:'Szukaj',
                        handler:function(){
                            $('#search-dialog-content').window('open');
                            var ddsv = $('#search-dialog-content').find('div.inside-serach');
                            ddsv.panel({
                                border:false,
                                modal:true,
                                height:50,
                                cache:false,
                                href:'/pl/sites/dialogs/serachitems',
                                onLoad:function(){

                                }
                            });
                        }
                    },
                    {
                        id:'btnsort',
                        text:'Zawęź',
                        handler:function(){

                        }
                    }
                    ,
                    {
                        id:'btnremove',
                        text:'Usuń',
                        handler:function(){

                        }
                    }
                ],
                columns:[[
                        {field:'icon',title:'Ikona',width:50},
                        {field:'name',title:'Tytuł',width:300},
                        {field:'date_add',title:'Data dodania (Edycji)',width:160,align:'center'},
                        {field:'action',title:'Akcja',width:90,align:'center'},
                        {field:'position',title:'Przenieś',width:70,align:'center'}
                    ]],
                onExpandRow: function(index,row){
                    //$('#tree-items').datagrid('rejectChanges');
                    var ddv = $(this).datagrid('getRowDetail',index).find('div.ddv');
                    ddv.panel({
                        border:false,
                        modal:true,
                        cache:false,
                        href:'/pl/sites/tree/edititem?id='+row.id,
                        onLoad:function(){

                            $('#tree-items').datagrid('fixDetailRowHeight',index);
                            $('#tree-items').datagrid('selectRow',index);

                            $('#tree-items').datagrid('getRowDetail',index).find('form').form('load',row);


                        }
                    });
                    $('#tree-items').datagrid('fixDetailRowHeight',index);

                }
            });



        }
    }


</script>


