
<div id="index-tree-edit-dialog" class="easyui-dialog" style="width:960px;height:450px"
     closed="false" title ="Edytuj drzewo kategorii"  buttons ="#dlg-buttons-tree-edit" >


                <div id="dlg-buttons-tree-edit">
                    <a href="#" class="easyui-linkbutton button-blue"  title ="Zapisz zmiany"  ><strong>Zapisz</strong></a>
                    <a href="#" class="easyui-linkbutton button-blue" title ="Zapisz zmiany"  ><strong>Zapisz i powróć</strong></a>
                    <a href="#" style ="float:left;" class="easyui-linkbutton button-blue" onClick =" back();" title ="Wróć do listy stron bez zapisu" >Wróć</a>
                </div>
            </div>
