<script type="text/javascript">
    $(document).ready(function() {
        $('#about-box-container').window();
    });
</script>
<div id ="about-box-container"   shadow ="false" class="easyui-dialog"  draggable ="true" resizable="true" closable ="false" title ="informacje o systemie" buttons="#dlg-buttons-action" >

    <div id="dlg-buttons-action">
        <h1><center>Unicorn CMS</center></h1>
        <h4>Witaj w systemie zarządzania trescią</h4>
        <table>
            <tbody>
                <tr>
                    <th>Autor:</th>
                    <th>Arnold Sikorski</th>
                </tr>
                <tr>
                    <th>Wersja systemu:</th>
                    <th>1.0</th>
                </tr>
                <tr>
                    <th>Strona projektu:</th>
                    <th>www.unicorn-cms.com</th>
                </tr>
            </tbody>
        </table>
        <a href="#" class="easyui-linkbutton button-blue" title ="Zmień swoje hasło dostepu do systemu"  ><strong>Zamknij okno</strong></a>
    </div>
</div>