<h2 class="corners">toplista</h2>
<!--<div class="news_item">
    <div class="news_item_main">
        <div class="news_item_img img_news"><img class="prize" src="/img/1_71.png" /></div>
        <div class="news_item_text">
            <h3>Przykładowy tytuł jakiegokolwiek artykułu na okolo 60 znaków</h3>
            <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki...</p>
        </div>
    </div>
    <div class="news_item_bottom">
        <span class="vote"></span>
        <span class="bar corners">
            <span class="news_item_date info">12.12.2011r</span>
            <span class="news_item_pkt info">+235pkt</span>
            <span class="news_item_pos info">135 miejsce</span>
            <span class="news_item_user info">DonPedro</span>
            <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
            <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
        </span>
    </div>
</div>
<div class="news_item">
    <div class="news_item_main">
        <div class="news_item_img img_news"><img class="prize" src="/img/1_67.png" /></div>
        <div class="news_item_text">
            <h3>Przykładowy tytuł jakiegokolwiek artykułu na okolo 60 znaków</h3>
            <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki...</p>
        </div>
    </div>
    <div class="news_item_bottom">
        <span class="vote"></span>
        <span class="bar corners">
            <span class="news_item_date info">12.12.2011r</span>
            <span class="news_item_pkt info">+235pkt</span>
            <span class="news_item_pos info">135 miejsce</span>
            <span class="news_item_user info">DonPedro</span>
            <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
            <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
        </span>
    </div>
</div>
<div class="news_item">
    <div class="news_item_main">
        <div class="news_item_img img_news"><img class="prize" src="/img/1_63.png" /></div>
        <div class="news_item_text">
            <h3>Przykładowy tytuł jakiegokolwiek artykułu na okolo 60 znaków</h3>
            <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki...</p>
        </div>
    </div>
    <div class="news_item_bottom">
        <span class="vote"></span>
        <span class="bar corners">
            <span class="news_item_date info">12.12.2011r</span>
            <span class="news_item_pkt info">+235pkt</span>
            <span class="news_item_pos info">135 miejsce</span>
            <span class="news_item_user info">DonPedro</span>
            <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
            <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
        </span>
    </div>
</div>-->
<div class="news_item">
    <div class="news_item_main">
        <div class="news_item_img img_news"><img class="prize" src="/img/1_71.png" /></div>
        <div class="news_item_text">
            <h3>Przykładowy tytuł jakiegokolwiek artykułu na okolo 60 znaków</h3>
            <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki...</p>
        </div>
    </div>
    <div class="news_item_bottom">
        <span class="vote"></span>
        <span class="bar corners">
            <span class="news_item_date info">12.12.2011r</span>
            <span class="news_item_pkt info">+235pkt</span>
            <span class="news_item_pos info">135 miejsce</span>
            <span class="news_item_user info">DonPedro</span>
            <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
            <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
        </span>
    </div>
</div>
  <div class="news_item_double">
                        <div class="news_item_main_double">
                            <div class="news_item_img img_news"></div>
                            <div class="news_item_text_double">
                                <h3>Przykładowy tytuł jakiegokolwiek</h3>
                                <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki</p>
                            </div>
                        </div>
                        <div class="news_item_bottom">
                            <span class="vote"></span>
                            <span class="bar_double corners">
                                <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
                                <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
                            </span>
                        </div>
                    </div>
                    <div class="news_item_double">
                        <div class="news_item_main_double">
                            <div class="news_item_img img_news"></div>
                            <div class="news_item_text_double">
                                <h3>Przykładowy tytuł jakiegokolwiek</h3>
                                <p>przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki, przykładowa treść artykułu, pierwsze 3 linijki</p>
                            </div>
                        </div>
                        <div class="news_item_bottom">
                            <span class="vote"></span>
                            <span class="bar_double corners">
                                <span class="news_item_more"><a class="corners" href="#more">czytaj dalej >></a></span>
                                <span class="news_item_category"><a class="corners news" href="#category">News</a></span>
                            </span>
                        </div>
                    </div>
<!--end-->