<div id="menu">
    <ul>
        <?php foreach($this->menu as $item): ?>
            <li><a href="/<?php echo $item['url']?>"><?php echo $item['name']; ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<!--
<ul>
        <li><a href="/news">News</a></li>
        <li><a href="/news/dzis-polityka">Polityka</a></li>
        <li><a href="#s">Biznes</a></li>
        <li><a href="#s">Sport</a></li>
        <li><a href="#s">Kultura</a></li>
        <li><a href="#s">Technika</a></li>
        <li><a href="#s">Zdrowie</a></li>
        <li><a href="#s">Publicystyka i inne</a></li>
    </ul>-->