<script type="text/javascript">

    $(document).ready(function() {


        $('#login-box-container').window({
            width:400
        });
<?php if ($this->result): ?>
<?php if ($this->change): ?>
                $.messager.alert('Hasło','<?php echo $this->msg; ?>');
<?php endif; ?>
<?php else: ?>
                    $.messager.alert('Problem','<?php echo $this->msg; ?>');
<?php endif; ?>
                });
                function generatePassword(){
                    /*Funckja genereujaca hasło**/

                    var RandomPassword = GeneratePassword();
                    if(RandomPassword){
                        var msg = 'Wybrałeś funkcje generującą hasło <br/>'
                            +'Twoje nowe hasło to: <strong>'+RandomPassword+'</strong><br/>'
                            +'Zapamietaj bądź zapisz hasło, a następnie wcisnij OK';

                        $.messager.confirm('Uwaga!',msg,function(r){
                            if (r){
                                $('#new_password').val(RandomPassword);
                                $('#new_password_repeat').val(RandomPassword);
                            }
                        });
                    }else{
                        /*hasło nie zostało wygenerowane*/
                        $.messager.alert('Problem','Nastąpił problem podczas generowania hasła!');
                    }
                }
                /*Submit formularza*/
                function sumbitChangePasswordForm(){
                    var isValid = $('#ChangePassword_form').form('validate');
                    if(isValid){


                        var new_password = $('#new_password').val();
                        var new_password_repeat = $('#new_password_repeat').val();

                        if(new_password == new_password_repeat){
                            $('#ChangePassword_form').submit();
                        }else{
                            $.messager.alert('Problem','Hasła nie są zgodne!');
                        }
                    }


                }
            </script>
            <div id ="login-box-container"  style ="padding:20px;" shadow ="false" class="easyui-dialog"  draggable ="true" resizable="true" closable ="false" title ="zmień swoje hasło dostępu" buttons="#dlg-buttons-action" >
    <?php echo $this->ChangePasswordForm; ?>

    <div id="dlg-buttons-action">
        <a href="#" class="easyui-linkbutton button-blue" style ="float:left;" onClick ="generatePassword();" title ="Wygenereuj hasło" >Wygeneruj</a>
        <a href="#" class="easyui-linkbutton button-blue" title ="Zmień swoje hasło dostepu do systemu"  onclick="sumbitChangePasswordForm()"><strong>Zmień</strong></a>
        <a href="#" class="easyui-linkbutton button-blue" title ="Zamknij okno" >Anuluj</a>
    </div>
</div>
