<div id="left_top">
    <h2 class="corners h2top h2topleft">top autorzy</h2>
    <h2 class="corners h2top h2notactive">top teksty</h2>
    <div class="autor">
        <div class="autor_img"></div>
        <div class="autor_info">
            <span class="autor_title">Autor miesiąca</span>
            <span class="autor_name info">DonPedro</span>
            <span class="autor_pkt info">+235pkt</span>
        </div>
        <div class="autor_vi"><img src="/img/1_60.png" /></div>
    </div>

    <div class="autor">
        <div class="autor_img"></div>
        <div class="autor_info">
            <span class="autor_title">Autor tygodnia</span>
            <span class="autor_name info">DonPedro</span>
            <span class="autor_pkt info">+235pkt</span>
        </div>
        <div class="autor_vi"><img src="/img/1_68.png" /></div>
    </div>

    <div class="autor">
        <div class="autor_img"></div>
        <div class="autor_info">
            <span class="autor_title">Autor dnia</span>
            <span class="autor_name info">DonPedro</span>
            <span class="autor_pkt info">+235pkt</span>
        </div>
        <div class="autor_vi"><img src="/img/1_74.png" /></div>
    </div>
    
    <div id="ads250">
        <?php echo $this->ad ?>
    </div>
</div>