<script type="text/javascript"> 
$(document).ready(function(){ 
});
</script>
<div id="site_top">
    <div class="text_site_top">kontakt</div>
</div>
<div id="site_left_content" class="kontakt">
        <h3 class="kontakt_h3">HALO FOTO</h3>
    <p class="kontakt_info">
        <span class="info_label">mail:</span> studio@halofoto.pl<br/>
        <span class="info_label">www:</span> www.halofoto.pl<br/>
        <span class="info_label">tel.:</span> +48 606 609 999<br/>
    </p>
</div>
<div id="site_right_content" class="kontakt_map">
    <a target="_blank" href="http://maps.google.pl/maps?hl=pl&ll=50.050526,19.942616&spn=0.019097,0.038581&t=h&z=15"><img src="/img/mapa.jpg"  width="575" height="330"/></a>
</div>
<style>
    .kontakt{
        width: 335px !important;
        margin-top: 125px !important;
    }
    .kontakt_info{
        text-align: center;
        line-height: 25px;
    }
    .kontakt_h3{
        text-align: center;
    }
    .info_label{
        color:#FBA81A;
    }
    .kontakt_map{
        float: left !important;
        height: 330px !important;
        width: 575px !important;
    }
</style>