<?php
$row = $this->request;
?>
<table>
    <tbody>
        <tr>
            <td><strong>Nazwa serwisu:</strong></td>
            <td>row 1, cell 2</td>
        </tr>
        <tr>
            <td><strong>URL systemu</strong></td>
            <td>row 1, cell 2</td>
        </tr>
        <tr>
            <td><strong>Język przeglądarki:</strong></td>
            <td>row 1, cell 2</td>
        </tr>
        <tr>
            <td><strong>Wersja przegladarki:</strong></td>
            <td>row 1, cell 2</td>
        </tr>
        <tr>
            <td><strong>Język:</strong></td>
            <td>row 2, cell 2</td>
        </tr>
        <tr>
            <td><strong>Login (jeśli zalogowany):</strong></td>
            <td>row 2, cell 2</td>
        </tr>
        <tr>
            <td><strong>Login (jeśli zalogowany):</strong></td>
            <td>row 2, cell 2</td>
        </tr>

        <tr>
            <td><strong>Tytuł:</strong></td>
            <td>row 2, cell 2</td>
        </tr>
        <tr>
            <td><strong>Opis problemu</strong></td>
            <td>dfdfd</td>
        </tr>
        <tr>
            <td><strong>Data:</strong></td>
            <td>row 2, cell 2</td>
        </tr>
        <tr>
            <td><strong>Email kontaktowy</strong></td>
            <td>row 2, cell 2</td>
        </tr>
    </tbody>
</table>